"use strict";

var ActionNames = {};

ActionNames.INITIALIZE_STORE = "INITIALIZE_STORE";
ActionNames.CHANGE_DOMAIN = "CHANGE_DOMAIN";
ActionNames.SHOW_NEW_MESSAGE_DIALOG = "SHOW_NEW_MESSAGE_DIALOG";
ActionNames.HIDE_NEW_MESSAGE_DIALOG = "HIDE_NEW_MESSAGE_DIALOG";
ActionNames.SUBMIT_NEW_MESSAGE = "SUBMIT_NEW_MESSAGE";
ActionNames.SUBMIT_NEW_CONTRADICTION = "SUBMIT_NEW_CONTRADICTION";
ActionNames.SELECT_MESSAGE = "SELECT_MESSAGE";
ActionNames.GO_PERPENDICULAR = "GO_PERPENDICULAR";
ActionNames.LEAVE_PERPENDICULAR = "LEAVE_PERPENDICULAR";
ActionNames.SHOW_CONTRADICT_WINDOW = "SHOW_CONTRADICT_WINDOW";
ActionNames.HIDE_CONTRADICT_WINDOW = "HIDE_CONTRADICT_WINDOW";
ActionNames.NEW_MESSAGE_SELECT_TAB = "NEW_MESSAGE_SELECT_TAB";
ActionNames.NEW_CONTRADICTION_SELECT_TAB = "NEW_CONTRADICTION_SELECT_TAB";
ActionNames.CREATE_SYMBOLIC_LINK = "CREATE_SYMBOLIC_LINK";
ActionNames.VIEW_DIALOG_PROPERTIES = "VIEW_DIALOG_PROPERTIES";
ActionNames.MAIN_SELECT_TAB = "MAIN_SELECT_TAB";
ActionNames.CHANGE_USER_SETTING = "CHANGE_USER_SETTING";
ActionNames.CONTRIBUTION_DELETE_LEAF = "CONTRIBUTION_DELETE_LEAF";
ActionNames.CONTRIBUTION_REMOVE_OWNERSHIP = "CONTRIBUTION_REMOVE_OWNERSHIP";
ActionNames.ADD_NEW_DOMAIN = "ADD_NEW_DOMAIN";
ActionNames.EDIT_MESSAGE = "EDIT_MESSAGE";
ActionNames.HIDE_EDIT_MESSAGE = "HIDE_EDIT_MESSAGE";
ActionNames.UPDATE_MESSAGE = "UPDATE_MESSAGE";
